version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ClusteredDH
      MYSQL_DATABASE: ClusteredDH_Db
      MYSQL_USER: ClusteredDH
      MYSQL_PASSWORD: ClusteredDH
    ports:
      - "3306:3306"

  app:
    build: .
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ClusteredDH_Db
      SPRING_DATASOURCE_USERNAME: ClusteredDH
      SPRING_DATASOURCE_PASSWORD: ClusteredDH
    volumes:
      - ./data:/var/lib/mysql
